### ISSUE TITLE
Setting minimum coverage levels

### ISSUE THREAD

**Issue by alexandermckay** [TransmissionsDev/merge-cypress-jest-coverage#1]
How would I be able to set minimum coverage levels using this tool?

**Comment by alexandermckay** [comment]
Worked it out.

**Comment by transmissions11** [comment]
oh wow it makes me so happy that someone is actually using this!

**Comment by TransmissionsDev** [comment]
@alexandermckay mind sharing your solution so others who have the same question can also resolve it?
